#!/usr/bin/env python3
import json
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent

# Create a simple README
readme = """# 💻 LeetCode Solutions

> Automatically updated with fresh statistics.

## 📊 Statistics
- Total Problems: Calculating...
- Easy: —
- Medium: —
- Hard: —

---

This is a test README generated by GitHub Actions.
"""

# Write it
readme_path = REPO_ROOT / "README.md"
with open(readme_path, 'w') as f:
    f.write(readme)

print("✅ README updated!")
